import Sidebar from "@/components/Sidebar"


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function UserLayout({ params, children }) {
  return (
    <div className="flex">
      <Sidebar params={params} />
      {children}
    </div>

  )
}
